on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set environment variables
        run: |
          echo "VERSION=$GITHUB_SHA" >> $GITHUB_ENV
          echo "LAUNCHER_NAME=${{ vars.LAUNCHER_NAME }}" >> $GITHUB_ENV
          echo "SERVER_BASE=${{ vars.SERVER_BASE }}" >> $GITHUB_ENV
          if [ -n "${{ vars.TGAUTH_BASE }}" ]; then echo "TGAUTH_BASE=${{ vars.TGAUTH_BASE }}" >> $GITHUB_ENV; fi
          if [ -n "${{ vars.ELYBY_APP_NAME }}" ]; then echo "ELYBY_APP_NAME=${{ vars.ELYBY_APP_NAME }}" >> $GITHUB_ENV; fi
          if [ -n "${{ vars.ELYBY_CLIENT_ID }}" ]; then echo "ELYBY_CLIENT_ID=${{ vars.ELYBY_CLIENT_ID }}" >> $GITHUB_ENV; fi
          if [ -n "${{ vars.ELYBY_CLIENT_SECRET }}" ]; then echo "ELYBY_CLIENT_SECRET=${{ vars.ELYBY_CLIENT_SECRET }}" >> $GITHUB_ENV; fi
          if [ -n "${{ vars.DISPLAY_LAUNCHER_NAME }}" ]; then
            echo "DISPLAY_LAUNCHER_NAME=${{ vars.DISPLAY_LAUNCHER_NAME }}" >> $GITHUB_ENV
          else
            echo "DISPLAY_LAUNCHER_NAME=${{ vars.LAUNCHER_NAME }}" >> $GITHUB_ENV
          fi

      - name: Build the launcher
        run: |
          mkdir -p launcher
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cargo build --release
            mv "target/release/potato_launcher.exe" "launcher/${DISPLAY_LAUNCHER_NAME}.exe"
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cargo build --release
            mv "target/release/potato_launcher" "launcher/${DISPLAY_LAUNCHER_NAME}"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            mkdir -p icon.iconset
            sips -z 16 16     "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_16x16.png
            sips -z 32 32     "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_16x16@2x.png
            sips -z 32 32     "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_32x32.png
            sips -z 64 64     "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_32x32@2x.png
            sips -z 64 64     "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_64x64.png
            sips -z 128 128   "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_64x64@2x.png
            sips -z 128 128   "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_128x128.png
            sips -z 256 256   "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_128x128@2x.png
            sips -z 256 256   "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_256x256.png
            sips -z 512 512   "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_256x256@2x.png
            sips -z 512 512   "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_512x512.png
            sips -z 1024 1024 "assets/$LAUNCHER_NAME.png" --out icon.iconset/icon_512x512@2x.png
            iconutil -c icns icon.iconset -o assets/icon.icns

            cargo install cargo-bundle
            cargo bundle --release

            mkdir -p app
            mv "target/release/bundle/osx/Potato Launcher.app" "app/$DISPLAY_LAUNCHER_NAME.app"

            codesign --force --deep --sign - "app/$DISPLAY_LAUNCHER_NAME.app"

            DMG_FILENAME="${DISPLAY_LAUNCHER_NAME}.dmg"
            hdiutil create "$DMG_FILENAME" -ov -volname "$DISPLAY_LAUNCHER_NAME" -fs HFS+ -srcfolder "app/"
            mv "$DMG_FILENAME" launcher/

            mv "app/$DISPLAY_LAUNCHER_NAME.app" "app/update.app"
            tar -czvf "launcher/${LAUNCHER_NAME}_macos.tar.gz" -C app "update.app"
          fi

          echo "$VERSION" > launcher/version.txt

      - name: Upload to server
        if: github.ref == 'refs/heads/rewrite-in-rust'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: no

      - name: Deploy to server
        if: github.ref == 'refs/heads/rewrite-in-rust'
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null launcher/* $SERVER_USER@$SERVER_ADDR:$SERVER_PATH/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: launcher-${{ matrix.os }}
          path: launcher/*
