on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set environment variables
        run: |
          echo "VERSION=$GITHUB_SHA" >> $GITHUB_ENV
          echo "LAUNCHER_NAME=${{ vars.LAUNCHER_NAME }}" >> $GITHUB_ENV
          echo "SERVER_BASE=${{ vars.SERVER_BASE }}" >> $GITHUB_ENV
          if [ -n "${{ vars.TGAUTH_BASE }}" ]; then echo "TGAUTH_BASE=${{ vars.TGAUTH_BASE }}" >> $GITHUB_ENV; fi
          if [ -n "${{ vars.ELYBY_APP_NAME }}" ]; then echo "ELYBY_APP_NAME=${{ vars.ELYBY_APP_NAME }}" >> $GITHUB_ENV; fi
          if [ -n "${{ vars.ELYBY_CLIENT_ID }}" ]; then echo "ELYBY_CLIENT_ID=${{ vars.ELYBY_CLIENT_ID }}" >> $GITHUB_ENV; fi
          if [ -n "${{ vars.ELYBY_CLIENT_SECRET }}" ]; then echo "ELYBY_CLIENT_SECRET=${{ vars.ELYBY_CLIENT_SECRET }}" >> $GITHUB_ENV; fi
          if [ -n "${{ vars.DISPLAY_LAUNCHER_NAME }}" ]; then
            echo "DISPLAY_LAUNCHER_NAME=${{ vars.DISPLAY_LAUNCHER_NAME }}" >> $GITHUB_ENV
          else
            echo "DISPLAY_LAUNCHER_NAME=${{ vars.LAUNCHER_NAME }}" >> $GITHUB_ENV
          fi

      - name: Build the launcher
        run: |
          cargo build --release
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            BINARY_PATH="target/release/potato_launcher.exe"
          else
            BINARY_PATH="target/release/potato_launcher"
          fi

          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            TARGET_FILENAME="${LAUNCHER_NAME}.exe"
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            TARGET_FILENAME="${LAUNCHER_NAME}_linux"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            TARGET_FILENAME="${LAUNCHER_NAME}_macos"
          else
            echo "Unsupported OS: ${{ matrix.os }}"
            exit 1
          fi

          mkdir -p launcher
          if [ "${{ matrix.os }}" != "macos-latest" ]; then
            mv "$BINARY_PATH" launcher/"$TARGET_FILENAME"
          else
            mkdir -p icon.iconset
            sips -z 16 16     assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_16x16.png
            sips -z 32 32     assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_16x16@2x.png
            sips -z 32 32     assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_32x32.png
            sips -z 64 64     assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_32x32@2x.png
            sips -z 64 64     assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_64x64.png
            sips -z 128 128   assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_64x64@2x.png
            sips -z 128 128   assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_128x128.png
            sips -z 256 256   assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_128x128@2x.png
            sips -z 256 256   assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_256x256.png
            sips -z 512 512   assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_256x256@2x.png
            sips -z 512 512   assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_512x512.png
            sips -z 1024 1024 assets/"$LAUNCHER_NAME".png --out icon.iconset/icon_512x512@2x.png

            mkdir -p app/"$DISPLAY_LAUNCHER_NAME".app/Contents/MacOS

            mkdir -p app/"$DISPLAY_LAUNCHER_NAME".app/Contents/Resources
            iconutil -c icns icon.iconset -o app/"$DISPLAY_LAUNCHER_NAME".app/Contents/Resources/icon.icns

            sed -e "s/\${DISPLAY_LAUNCHER_NAME}/$DISPLAY_LAUNCHER_NAME/g" \
                -e "s/\${LAUNCHER_NAME}/$LAUNCHER_NAME/g" \
                assets/Info.plist > app/"$DISPLAY_LAUNCHER_NAME".app/Contents/Info.plist

            cp "$BINARY_PATH" app/"$DISPLAY_LAUNCHER_NAME".app/Contents/MacOS/"$LAUNCHER_NAME"

            DMG_FILENAME="${DISPLAY_LAUNCHER_NAME}.dmg"
            hdiutil create "$DMG_FILENAME" -ov -volname "$DISPLAY_LAUNCHER_NAME" -fs HFS+ -srcfolder "app/"
            mv "$DMG_FILENAME" launcher/

            tar -czvf launcher/"$LAUNCHER_NAME".tar.gz app/"$DISPLAY_LAUNCHER_NAME".app
          fi

          echo "$VERSION" > launcher/version.txt

      - if: ${{ github.ref }} == rewrite-in-rust
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: no

      - if: ${{ github.ref }} == rewrite-in-rust
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
        run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null launcher/* $SERVER_USER@$SERVER_ADDR:$SERVER_PATH/

      - uses: actions/upload-artifact@v4
        with:
          name: launcher-${{ matrix.os }}
          path: launcher/*
